/**
 * Bot levels (GDD §12.5): node budgets and the search shape of each planner.
 *
 * Budgets count NODE EXPANSIONS, never time: one expansion is one simulated action (a child
 * node generated by applying an action to a planning state and scoring it), including the
 * actions a one-round lookahead simulates. The wall-clock cap from `bots.json` is only a safety
 * net: when it trips, the planner stops and returns the best plan found so far.
 */
import type { BotLevel, ContentRegistry } from '../types';

export interface LevelProfile {
  level: BotLevel;
  /** Node expansions per seat turn (`bots.json` nodeBudget). */
  budget: number;
  /** Safety net only (`bots.json` wallClockMs). */
  wallClockMs: number;
  /** Greedy hill-climb (beam of 1, kills first) instead of a beam search. */
  greedy: boolean;
  /** Nodes kept per depth. */
  beamWidth: number;
  /** Candidate actions generated per node (after pruning). */
  maxCandidates: number;
  /** Move destinations kept per piece (top-K by the move prior). */
  movesPerPiece: number;
  /** Target combinations kept per card (and for the Hero Power). */
  playsPerCard: number;
  /** Final plans re-scored with a one-round lookahead (0 = none). */
  lookahead: number;
  /** Last Flame: weight of the best rival's Glory (subtracted), relative to own Glory. */
  rivalGlory: number;
  /** Deepest plan considered (actions before end_turn). */
  maxDepth: number;
}

const SHAPES: Record<BotLevel, Omit<LevelProfile, 'level' | 'budget' | 'wallClockMs'>> = {
  bot_apprentice: { greedy: true, beamWidth: 1, maxCandidates: 18, movesPerPiece: 3, playsPerCard: 3, lookahead: 0, rivalGlory: 0, maxDepth: 10 },
  bot_warden: { greedy: false, beamWidth: 5, maxCandidates: 28, movesPerPiece: 4, playsPerCard: 4, lookahead: 0, rivalGlory: 0.15, maxDepth: 14 },
  bot_elder: { greedy: false, beamWidth: 18, maxCandidates: 52, movesPerPiece: 8, playsPerCard: 8, lookahead: 16, rivalGlory: 0.4, maxDepth: 16 },
};

const FALLBACK = { bot_apprentice: [200, 2000], bot_warden: [2000, 4000], bot_elder: [20000, 8000] } as const;

export function levelProfile(level: BotLevel, reg: ContentRegistry): LevelProfile {
  const def = reg.bots.byId[level];
  const [budget, wallClockMs] = FALLBACK[level];
  return { level, budget: def?.nodeBudget ?? budget, wallClockMs: def?.wallClockMs ?? wallClockMs, ...SHAPES[level] };
}

/**
 * Counts node expansions against the level's budget. The clock is read only to enforce the
 * wall-clock safety net; with a generous cap the plan depends on the state alone.
 */
export class Budget {
  private used = 0;
  private timedOut = false;
  private readonly deadline: number;

  constructor(
    readonly limit: number,
    wallClockMs: number,
    private readonly now: () => number,
  ) {
    this.deadline = now() + wallClockMs;
  }

  /** Take one expansion; false when the budget (or the safety-net clock) is exhausted. */
  spend(): boolean {
    if (this.exhausted()) return false;
    this.used += 1;
    return true;
  }

  exhausted(): boolean {
    if (this.used >= this.limit || this.timedOut) return true;
    if (this.used % 8 === 0 && this.now() > this.deadline) this.timedOut = true;
    return this.timedOut;
  }

  get expansions(): number {
    return this.used;
  }

  get hitClock(): boolean {
    return this.timedOut;
  }
}

/** The default clock: `performance.now()` (browsers, workers and Node all provide it). */
export function defaultClock(): () => number {
  const perf = (globalThis as { performance?: { now(): number } }).performance;
  return perf ? () => perf.now() : () => 0;
}
